{% set name = "pyclean" %}
{% set version = "3.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyclean-{{ version }}.tar.gz
  sha256: a48be7afd512b1923a7b9decc1219bbbe2d73199c939b46c936448f904a180ce

build:
  entry_points:
    - pyclean = pyclean.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.5
    - setuptools >=44
    - pip
  run:
    - python >=3.5

test:
  imports:
    - pyclean
  commands:
    - pip check
    - pyclean --help
  requires:
    - pip

about:
  home: https://github.com/bittner/pyclean
  license: GPL-3.0-or-later
  license_file: LICENSE
  summary: Pure Python cross-platform pyclean. Clean up your Python bytecode.

extra:
  recipe-maintainers:
    - bittner
